import img from '../asset/images'
const product = [
    {
        img: img.men_1,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 1',
    },
    {
        img: img.men_2,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 2',
    },
    {
        img: img.men_3,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 3',
    },
    {
        img: img.men_4,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 4',
    },
    {
        img: img.men_5,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 5',
    },
    {
        img: img.men_6,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 6',
    },
    {
        img: img.men_7,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 7',
    },
    {
        img: img.men_8,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 8',
    },
    {
        img: img.men_9,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 9',
    },
    {
        img: img.men_10,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 10',
    },
    {
        img: img.men_11,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 11',
    },
    {
        img: img.men_12,
        pathDetai: '/',
        addCart: '/',
        cost: '675.00',
        promotional_price: '580',
        name: 'men 12',
    },
];

export default product;