const img = {
    logo: require('./logo/download.webp'),
    logoFooter: require('./logo/xlogo2_footer.png.pagespeed.ic.DUxRn4vG1w.webp'),
    logoBanner: require('./hero/xh1_hero1.jpg.pagespeed.ic.i78C8XcvnM.webp'),
    logoProduct_1: require('./gallery/xitems1.jpg.pagespeed.ic.oEs2Is3V_r.webp'),
    logoProduct_2: require('./gallery/xitems2.jpg.pagespeed.ic.rorSvQkHIK.webp'),
    logoProduct_3: require('./gallery/xitems3.jpg.pagespeed.ic.oIlAW2CB1j.webp'),
    logoLatest_1: require('./gallery/xlatest4.jpg.pagespeed.ic.Lrd0UW2ap9.webp'),
    logoLatest_2: require('./gallery/xlatest1.jpg.pagespeed.ic.9LywwGvNeR.webp'),
    logoLatest_3: require('./gallery/xlatest3.jpg.pagespeed.ic.weRwbGvwtF.webp'),
    logoLatest_4: require('./gallery/xlatest2.jpg.pagespeed.ic.wreJQIyLHL.webp'),
    maylike_1: require('./may-like/xlatest5.jpg.pagespeed.ic.WuUZFTYF8g.webp'),
    maylike_2: require('./may-like/xlatest6.jpg.pagespeed.ic.Gs5H8uF_0V.webp'),
    maylike_3: require('./may-like/xlatest7.jpg.pagespeed.ic.hx4jI0dHK5.webp'),
    maylike_4: require('./may-like/xlatest8.jpg.pagespeed.ic.qoQf2-mhtF.webp'),
    maylike_5: require('./may-like/7e0ccd8b93aebefcb20c07c0b023f913.jfif'),
    lastNew_1: require('./last-new/xblog1.jpg.pagespeed.ic.s1W931fRN7.webp'),
    lastNew_2: require('./last-new/xblog2.jpg.pagespeed.ic.JaQe05m-gL.webp'),
    lastNew_3: require('./last-new/xblog3.jpg.pagespeed.ic.hExcbkUXD4.webp'),
    men_1: require('./men/men_1.jpg'),
    men_2: require('./men/men_2.jfif'),
    men_3: require('./men/men_3.jfif'),
    men_4: require('./men/men_4.png'),
    men_5: require('./men/men_5.jpg'),
    men_6: require('./men/men_6.jpeg'),
    men_7: require('./men/men_7.webp'),
    men_8: require('./men/men_8.jpg'),
    men_9: require('./men/men_9.jpg'),
    men_10: require('./men/men_10.jpg'),
    men_11: require('./men/men_11.jpg'),
    men_12: require('./men/men_12.jpg'),
    women_1: require('./women/women_1.jfif'),
    women_2: require('./women/women_2.jfif'),
    women_3: require('./women/women_3.jfif'),
    women_4: require('./women/women_4.jfif'),
    other_1: require('./other/loi-khuyen-thoi-trang-a.jpg'),
}
export default img;